add_executable(cudatile-to-mlir
  cudatile-to-mlir.cpp
)

target_link_libraries(cudatile-to-mlir
  PRIVATE
  CudaTileToMLIR
  MLIROptLib
  MLIRArithDialect
  MLIRFuncDialect
  MLIRFuncInlinerExtension
  MLIRGPUDialect
  MLIRMemRefDialect
  MLIRSCFDialect
  MLIRUBDialect
  MLIRVectorDialect
  MLIRTransforms
  MLIRTransformUtils
  MLIRPass
  MLIRIR
  MLIRSupport
  CudaTileDialect
)
